### ISSUE TITLE
Cannot import the package

### ISSUE THREAD

**Issue by s60123685** [PMEAL/porespy#303]
My environment:
Spyder 4.1.4
Python 3.8

I have successfully install porespy 1.2.0
However, I have received an IndexError when I import the package.

Below shows the error information:
_________________________________
Traceback (most recent call last):

  File "<ipython-input-3-d90270dc439c>", line 1, in <module>
    import porespy

  File "C:\Users\User\anaconda3\lib\site-packages\porespy\__init__.py", line 87, in <module>
    from . import networks

  File "C:\Users\User\anaconda3\lib\site-packages\porespy\networks\__init__.py", line 34, in <module>
    from .__funcs__ import add_boundary_regions

  File "C:\Users\User\anaconda3\lib\site-packages\porespy\networks\__funcs__.py", line 3, in <module>
    import openpnm as op

  File "C:\Users\User\anaconda3\lib\site-packages\openpnm\__init__.py", line 64, in <module>
    from . import algorithms

  File "C:\Users\User\anaconda3\lib\site-packages\openpnm\algorithms\__init__.py", line 13, in <module>
    from .GenericTransport import GenericTransport

  File "C:\Users\User\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 102, in <module>
    class GenericTransport(GenericAlgorithm):

  File "C:\Users\User\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 217, in GenericTransport
    @docstr.get_full_descriptionf(base='GenericTransport.reset')

  File "C:\Users\User\anaconda3\lib\site-packages\docrep\decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)

  File "C:\Users\User\anaconda3\lib\site-packages\docrep\__init__.py", line 974, in get_full_descriptionf
    return self.get_full_description(base=args[0], *args[1:], **kwargs)

IndexError: tuple index out of range

**Comment by jgostick** [comment]
try updating openpnm (a dependency of porespy). One of it's dependencies pushed some breaking changes, which we've since patched.  Do ``pip install --update openpnm``

**Comment by s60123685** [comment]
It works. Thank you very much.
